server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    name: bear_boh
    url: jdbc:mysql://127.0.0.1:3306/bear_boh
    username: root
    password: 8888
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#Mybatis配置
mybatis:
  #实体类的包路径
  typeAliasesPackage: com.bearbaba.orginterface.bean
  #mapper文件路径
  mapperLocations: classpath:mapping/*.xml


  #打印Mybatis的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
